### ISSUE TITLE
rename xx.mtx.wav to xx.mtx?

### ISSUE THREAD

**Issue by tjingboem** [gesellkammer/loristrck#2]
Hello mr. Moguillansky,

3 months ago i posted https://github.com/csound/manual/issues/524 
i was just now about to rename fox.mtx.wav to fox.mtx in these 2 examples, but, without having tried your program loristrck, wanted to check with you if loristrack does indeed produce a wav file or it could just as well named .mtx?

**Comment by gesellkammer** [comment]
The file is indeed as wav file, with the difference that the wav format is used as a binary exchange format, thus avoiding more brittle solutions. But since csound does not depend on the extension of the file to determine the type then I see no problem in renaming the file to .mtx

**Comment by tjingboem** [comment]
i'd like to include this remark in the text if you don't mind as i think it really adds relevant information.
Then, in both examples, i will rename it to .mtx.
What do you think?

**Comment by tjingboem** [comment]
fox.mtx.wav is now fox.mtx- thanks!
