### ISSUE TITLE
doc loristrck_analyze error

### ISSUE THREAD

**Issue by tjingboem** [gesellkammer/loristrck#6]
one of the arguments for loristrck_analyze is not correct on the manual page

`--sdiftype SDIFTYPE: One of 'rbep' or '1trk' (case is ignored)`

should be

`--sdiftype SDIFTYPE: One of 'rbep' or '1trc' (case is ignored)`

https://loristrck.readthedocs.io/en/latest/commandline.html

**Comment by gesellkammer** [comment]
Thanks, fixed now
